### ISSUE TITLE
about initial Motion

### ISSUE THREAD

**Issue by Zericoo** [hmf21/UAVLocalization#1]
Hi！
I am a rookie in this area,I saw your comment under 'GPS-denied-uav-localization' post and I sincerely want to ask you, if I want to use this program to run my own uav images, how do I get the motion parameters in the '.csv' file containing the information of each uav image frame. If you have time to reply me, I would be very grateful.

**Comment by hmf21** [comment]
> 

Hello, the author of the original repository stores all the relative motion parameter 'p' in the '.cvs' file. and besides there is also the initial motion parameter. So if you want to test your own query image 
For the relative motion parameters, you could how to calculate it within 'sift_ransac_homography.py' file, which use 'cv2.findHomography' function to get the relative motion parameter between two query images from UAV. 
For the initial motion parameter, the author assume that the initial position of the taking off place is known, but it is a question about how to get the motion parameter. You could refer the 'main' function in 'DeepLKBatch.py' file, where parameter 'p' is calculated depends on the angle, translation and scale. So if you know the initial angle, translation and scale for the first frame against the map, you could get the initial motion parameter using that formular. 
Although it may hard to understand, I think reading the original repsitory carefully can help you better understand.
For the running mode, you can calculate all of the parameters and store them just like the author. You could also calculate the parameter meanwhile the uav flying. In that case, you should modify a little bit for the main programm in 'pose_opt.py' file. If you understand the programm well, it is also not a difficult task.

**Comment by Zericoo** [comment]
Thank you so much for your help, I'll try to work it out! Thank you again and good luck with your research!

**Comment by hmf21** [comment]
@Zericoo 
The same with you and hope you everything goes smoothly~

**Comment by Zericoo** [comment]
Hello, I'm very sorry to bother you again.&nbsp;
In the last few days I have studied the original program for calculating the parameter p, and your modified program. But my technology and strength is limited, using the satellite images and UAV images used in the paper still did not reproduce the '.csv' that came with the original paper, in which the difference between the parameters obtained and the original parameters is large. When calculating the initial parameters, I am not sure how to get the scale, angle, projective_x, projective_y, translation_x, translation_y in the original program. After reading your program, I admire it very much, but I have some doubts, so I would like to ask you.
In your modified 'sift_ransac_homography.py', the 'cal_P_init()' function contains the GPS of the satellite map, the pixel width and height of the satellite map, and the GPS of the drone image, and I would like to ask you which of 'I_height', 'I_width' and 'D_height', 'D_width' One pair is the drone image size, and what the other pair indicates?&nbsp;
' x_coor_init' and 'y_coor_init' are how to set?
The last question is, how are the coordinate matrices of the source and target set when using the 'cv2.findHomography()' function.


Sorry again for&nbsp; disturbance, and I would be really appreciate if you could reply to me in your busy schedule.

**Comment by hmf21** [comment]
Hi @Zericoo! Due to my poor English expressions, I try my best to explain the program what I have done. And hope it might help you.
The 'cal_P_init()' function in the modified 'sift_ransac_homography.py' file actually just an incomplete version for test. Sorry I haven't upload the latest version of my programm because I am writing an paper based on this project. Another function that I currently use to calculate the initial parameter 'p' is offered bellow. 
Where the 'init_x' and 'init_y' is the cordinate for the initial frame in the map (not the longitude and latitude). For dataset village offered by the original program, they are about 2747 and 924. And for another dataset you could manually mark in the map or convert using the GPS. 
Parameter 'scale' is the scale transformation between query image and reference map. You need to give the ratio of the width of query image to the width of map. For example, if you have the map with two kilometers width and the query image with five hundred meters width. The parameter 'scale' is 1/4. For dataset village offered by the original program, 'scale' is equal to 1/6.
Parameter 'angle' is the angle between initial frame and reference map (radian concept). For dataset village offered by the original program, 'angle' is equal to - pi / 2.
When using the 'cv2.findHomography()' function, it is also like this `H_found, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, 5.0)`. And the 'src_pts' corresponds the previous frame and ‘dst_pts’ corresponds  the current frame. For the details, you can refer to 'get_param()' function.
The original program is hard to understand to some kind, but it contains the answer for your questions such as how to calculater the initial parameter. You could carefully read the original 'sift_ransac_homography.py' file and 'extract_map_templates()' function in 'pose_opt.py' file. Hope I could do my favour. 

```
def test_init_P(init_x, init_y, w, h, scale, angle):
    t_x = init_x - w /2
    t_y = init_y - h /2
    H_standard_inv = [scale * math.cos(angle), -scale * math.sin(angle), t_x,
                        scale * math.sin(angle), scale * math.cos(angle), t_y,
                        0, 0, 1]
    H_standard_np_inv = np.array(H_standard_inv).reshape((3,3))
    H_standard_np = np.linalg.inv(H_standard_np_inv)
    P_standard_np = np.reshape(H_standard_np - np.eye(3), (9, 1))
    P_standard = np.expand_dims(P_standard_np[:8], 0)

    H_all_inv = p_to_H(P_standard)
    H_all = np.linalg.inv(H_all_inv)
    P_init = H_to_p(H_all)

    return P_init
```

**Comment by Zericoo** [comment]
Hello, thank you very much for your last reply. I didn't send an email reply to you because I was worried that frequent emails might disturb you.
After your last reply, I used your program 'test_init_P' for calculating the initial parameter P. The program used in the call is as follows. And I used the original downloaded program 'get_param' to calculate the relative motion parameters, but the parameters P obtained were different from those in the original dataset, and using the parameters P calculated by myself as the input to the program was very poor in matching the village dataset. I have been researching for a week but still have not figured out the reason for this. In the call to 'get_param', all the UAV images need to be read first, I use the 'load_I' function defined in the original program here, and the output is the image that resized to100*133 , I am not sure if this is the correct operation. I'm sorry to bother you again based on the above problem.


P_init = test_init_P(2747,924,4800,2861,1/6,-pi/2)


Original Parameters



Self-calculated parameters







Letter from a rookie./(ㄒoㄒ)/~~

**Comment by hmf21** [comment]
Hi @Zericoo , never mind and it is delighted to discuss with you.
You just say the result for init param and the relative param are both wrong, is it right? Only for the village dataset, I think you can consider the following points:
1, Can you test the initial parameter using P_init = test_init_P(2747,924,4800,2861,1/6,-3pi/4). Sorry, I just check it again and found the angle is -3pi/4.
2, For the relative parameters, 'get_param' function receive three parameters and please make sure they are right. 'img_batch' is the newly frame and 'template_batch' are the former frame. And the third parameter 'image_sz' is the true size(height) in the program. Because maybe the original frame has high resolution and we will use for example 'Image.Resize()' function. Please make sure you give the size after resize. For the original author 'sift_ransac_homography.py' file seems to be incomplete, because he only give two parameters (refer to [link](https://github.com/hmgoforth/gps-denied-uav-localization/blob/5aee540f08f85fee8dee6d6155c051da3ef38425/deep_feat/sift_ransac_homography.py#L157)).
3, Do you completely run these two dataset using the original program? Although you want to test your own dataset, but figure out how to run successfully the already existing dataset might help you better understand

Last, I can offer the program that I use to calculate the relative parameters and you could refer. The 'get_param' function is the same as the original author. 

If you have any problem, you can ask me anytime.

```
I_list, _ = img_utility.load_I(image_dir, ext=image_dir_ext, scaled_im_height=img_h_rel_pose)
p = []
P_init = test_init_P(2747,924,4800,2861,1/6,-3pi/4)
p.append(np.array(P_init))
# p.append(np.zeros([1, 8, 1]))
for i in range(I_list.shape[0]-1):
I_1 = I_list[i:i + 1, :, :, :]
I_2 = I_list[i + 1:i + 2, :, :, :]
template_batch = Variable(torch.from_numpy(I_1).squeeze(0))
img_batch = Variable(torch.from_numpy(I_2).squeeze(0))
tmp = get_param(img_batch, template_batch, img_h_rel_pose)
p.append(np.array(tmp))
np.savetxt(motion_param_loc, np.squeeze(np.array(p)), delimiter=',')
```

**Comment by Zericoo** [comment]
Hi,@hmf17
 thank you so much, I do still have doubts. 
1. about the initial param: when calculating the initial function, I used your program: 
```
  H_standard_inv = [scale*cos(angle), -scale*sin(angle), t_x,scale*sin(angle), scale*cos(angle ), t_y,0, 0, 1]. 
  P_init = test_init_P(2747,924,4800,2861,1/6,-3/4*pi)
```
we get [-1.11785 0.11785 347.00000 -0.11785 -1.11785 -506.50000 0 0 ] after calculation. 
And the initial param in the original file 'P_village.csv' are: [-5.2011 -5.9628 -1329.9  5.9628 -5.2011 -4536.2 0 0]
For example, the value of the first element is -5.2011, where the corresponding formula is scale*cos(angle), cos function 
value is in [-1, 1] , the result is then multiplied with scale, we can only get a number with absolute value less than 1. Even if 
the subsequent processing of 'H_standard_inv' is done, it is impossible to get a number with an absolute value greater than 2, much less -5.2011 in the original file.

2. About the relative parameters: I used the program you just posted,：
    tmp = get_param(img_batch, template_batch, opt_img_ height), where 'opt_img_height' is equal to 100, the same value as 
     used here for loading UAV images. i_list = load_I(image_dir, image_dir_ext, opt_img_height), and also get the difference in results.
    These questions have been bothering me for a long time, so I would like to ask you for advice.
    Thanks again.

**Comment by hmf21** [comment]
Hi @Zericoo, my thoughts are as follows:
1. the result should use inverse form, and it seems that you get the wrong initial parameter which is lack of inverse. The result I calculate is (using MATLAB) 
![image](https://user-images.githubusercontent.com/48024732/162751288-08b64f59-f501-4140-9c0f-aa9fafa2cb60.png)
and it is close to the standard parameter (even though they are quite different numerically, the match result is right). For the doubts about the range of parameter value, because the ariginal author use inverse function when load parameters (refer [link](https://github.com/hmgoforth/gps-denied-uav-localization/blob/5aee540f08f85fee8dee6d6155c051da3ef38425/optimize/pose_opt.py#L1766)). So the .csv file might contain the values that are beyond 2.
2. Could you test 'opt_img_height' is equal to 1036.8? 'img_h_rel_pose' the ariginal author offered is equal to 1036.8 and the 'opt_img_height' is supply for the CNN process. But I think the absolute value might make sense. Because when the parameter act on matching, things seems to be different. The entirely different parameter might result in same. You could check the extracted image patch when program running to see how does the current method works.

**Comment by Zericoo** [comment]
Hello @hmf17 
Sorry to disturb you again after a long time. I was busy with my studies before and didn't continue my research. Recently, I started learning this program again. After your teaching, I have reproduced the initial motion parameters of the village data set, but I have two questions in the calculation of the initial parameters : 
1. about the parameter'scale', the village dataset should have a pixel size of 4800 × 2861, 0.45 meters per pixel, so the map is 2160 × 1287 meters. UAV image pixels are 4608 × 3456, 5cm per pixel, so each UAV image is 230 × 173 meters, so I want to ask how I got this scale=1/6. 
2.  about the parameter 'angle': how to get the angle? If the horizontal direction is the X axis and the vertical direction is the Y axis to establish a coordinate system, the direction of the main road of the map image is about -135 ° and the main road of the UAV image is 90 °. From the UAV image to the direction of the map image, it needs to rotate 135 ° counterclockwise, so the angle=-135 °?
Finally, about rel parameters, the part of the code I ran was as follows.
```
opt_img_height = 1036
tmp = get_param(img_batch, template_batch, opt_img_height)
```
```
H_found, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, 3.0)
H = torch.from_numpy(H_found).float()

I = torch.eye(3, 3)
p = H - I
p = p.view(1, 9, 1)
p = p[:, 0:8, :]
p = p * 3
```
Is the operation of 'H_found' correct? Can the parameter 'p' be directly output in this way? Or do i need other operations
Thank you for your help all this time.

**Comment by hmf21** [comment]
Hello @Zericoo , I am glad to see you again and hope you have dealt well with your studies task.
About these questions:
1. For the parmeter 'scale', it is the ratio of the width of query image to the width of map as I declared above. And the height of the map is 1287 meters along with the height of 173 meters for UAV image, so the ratio is about 1/7.4. It is worth to say that the scale does not have to be very accurate, so I use the scale as 1/6. Also we calculate the ratio with the height of the image rather than the width, because when we align the UAV to the satellite map with the same image resolution, the re-sampled UAV image pixel is 3814 x 2861, so the map is wider than the UAV image, so the height is the key factor to calculate the parameter 'scale'.
2. About the parameter ‘angle', your explaination is right.
3. I don't understand the equation 'p =p * 3', what is the special meaning of the equation? The other equations seem to be correct.

**Comment by Zericoo** [comment]
Hello @hmf17 ，thank you very much for your answer.Unfortunately, I still can't get the correct rel parameters.May i ask have you correctly reproduced all parameters of the 'village'data set？
I used the program you modified. Maybe the program when reading pictures is different from yours? I simply used the'load provided in the original program_ I', obtained 'I_ list' : (17,3,1036,1381).
The main program I run is as follows:
![image](https://user-images.githubusercontent.com/102302665/177681681-ffcf9426-d259-4d97-8a80-f9a2d4c46bae.png)
The results are as follows:
![image](https://user-images.githubusercontent.com/102302665/177682450-40070f58-5487-467f-a1e5-71b9fbb40397.png)
Parameters used in the downloaded original paper:
![image](https://user-images.githubusercontent.com/102302665/177682631-c2dd882d-458e-4070-a5ba-2b5f27e313ed.png)

Last, about 'p =p * 3'：
Because the rel parameters I calculated are about three times different from those in the original paper, I tried to multiply by 3 to narrow the gap, but the results are still inaccurate. 
I've been bothered by the input parameters for a long time, and I'm sorry to disturb you often.

**Comment by hmf21** [comment]
Hi @Zericoo 
I think you could set the parameter 'opt_img_height' equal to 2861, which is the height of the satellite map. In that case, the result will more similar to the original paper. Because the author is also calculate the relative pose for the query frames in the same resolution as the map. Likely, the reason for the your result are about three times different from those in the original paper is the resolution of the map is about three times than the queried frames.
Moreover, you can use function 'scale_P' if you think your result has three different from the ground truth rather than directly times it by three. 
If there are still any problems, you can mention me. I am very glad to discuss with you!

**Comment by Zericoo** [comment]
Hi@hmf17 
Thank you very much indeed,after your many instructions, I finally reproduced the motion parameters of the village data set. Although there are still differences in the values, the running results are good. So I used the same method in grave_ Pit dataset and my own dataset, but where gravel_ Pit and some of its own data sets have errors. 
I found that when the angle between the UAV image and the satellite map is ± 1/2*pi, the calculating of the initial parameters will appear wrong data, because cos (± 1/2*pi) =0.
I'd like to ask you whether this is the reason why there are error results after running the program? If so, how did i correct it？

**Comment by hmf21** [comment]
Hi @Zericoo I am very glad to hear that you can reproduce the motion parameters after long time debugging.  Congratulations!
And what is the wrong with the angle with 1/2 pi? I test my own dataset with angle equal to 0 and 1/2pi and it is still work.
I think it doesn't matter if cos(angle) or sin(angle) equal to 0. What is your opinion?

**Comment by Zericoo** [comment]
Hi@hmf17  I should have misunderstood
When reproducing the motion parameters of gravel pit dataset, the parameter I use is as follows:
 ```
opt_img_height = 3456
P_init = init_P(2581, 980, 3355, 1852, 1 / 3, -1/ 2 * pi)
```
I use 'opt_img_height = 3456', because when reproducing the village data set, I found that 3456 has a better effect than 2861.
The results are as follows:
The positioning result of the first satellite map is accurate, but the warp result is very strange.
![image](https://user-images.githubusercontent.com/102302665/178930865-2d066ca3-5de4-4a1e-9e1c-339148f2b1c7.png)

**Comment by hmf21** [comment]
Hi @Zericoo Hahh, I think the wrong result is affected by the Deep-LK warping network because the initial satellite map is not accurate enough. I caculate the initial parameter with the configurations bellow:

![image](https://user-images.githubusercontent.com/48024732/178987849-195dd7e0-ed43-4ad0-b3a3-cdbcb8566aad.png)
You can try the configurations.

By the way, I just found that every time I receive you reply when I am ready to go off work because now is 9:00 pm in China. Hahhh!

**Comment by Zericoo** [comment]
Hi@hmf17 Hahh,sorry for delay your work. I'll try to email you in the morning. XD

The optimization algorithm proposed in the paper is implemented by 'optimize_ wamp' function . But when I call it, I get 'p_ opt_ i_  Scale',but on line 951 of the program,'p_ opt_ i_ Scale' is replaced by another value. Should I delete this line?

![image](https://user-images.githubusercontent.com/102302665/180335818-74528726-7900-495e-be7f-c17cf8a63f80.png)

I found that after I added the optimizer, the effect was not very good. Is it because there is an error in calling the method of optimizing the code.

In addition, I noticed that in your main program, you added the process of updating parameters circularly, from coarse to fine. After adding this program, I found that it will make the running result very stable, but the difference between 'M' and'M_warp' is very small. Is this normal?
![image](https://user-images.githubusercontent.com/102302665/180335870-e88abab3-7ddc-47d9-b960-fb028b3d1426.png)

Thank you again for your guidance！

**Comment by hmf21** [comment]
Hi @Zericoo, good morning, I am very glad to see you have made a big progress.

For the first question, sorry I don't remember the detail about the the original code at present. I recommand you do not modify the code until you completely figure it out. Because may be somewhere goes wrong after deleting it.

For the optimizer,  I also found that it is not work pretty good in the original code. With some parameter configurations, it can works well to optimize the localization result, while it oftenresults in a bad alignment too. 

Therefore I delete this part and use a coarse-to-fine strategy, it also works well just as you have noticed. The difference between 'M' and'M_warp' is very small, that is because in the plot part, 'M' is actually the result 'M_warp' from last alignment loop, rather than the original cropped map patch. Therefore, the difference between them are very small. You can modify the plot part to show the original cropped map patch.
